### ISSUE TITLE
Docker Database automatic "backups" (local copies) + automatic container updates

### ISSUE THREAD

**Issue by anonym-HPI** [hpi-sam/digital-fuesim-manv#656]
To help people to host this easier, we should give an option to enable automatic copies locally, to mitigate errors produced by migrations or so.
Also an automatic update process should be introduced, e.g. with the help of watchtower, but the watchtower should only update docker containers of this docker-compose.yml, to not interfere with other stuff on a server/computer.

For watchtower right now using the following, but labels for all containers inside docker-compose.yml should be added, to not interfere with other stuff.
```
    watchtower:
       image: containrrr/watchtower
       restart: unless-stopped
       environment:
           - WATCHTOWER_INCLUDE_RESTARTING=true
           - WATCHTOWER_SCHEDULE=0 0 4 * * *
           - WATCHTOWER_TIMEOUT=30
       volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/localtime:/etc/localtime:ro

```

Also documentation should be good and easy to understand. Also documentation should include that the local copy of the database is not a real backup and a real backup needs to be on another server/computer and easiest way: just export important exercises.
If and what should be enabled by default and maybe controlled via ENVs, can be discussed.

Not high priority, just a quality of life feature, for new people in the whole docker and deployment world.
